spring:
  application:
    name: foo-proc
  cloud:
    function:
      definition: processFoo
    stream:
      defaultBinder: rabbit
      function:
        bindings:
          processFoo-in-0: input
          processFoo-out-0: output
      bindings:
        input:
          destination: foo-source
          group: foo-source-group
          consumer:
            maxAttempts: 4
            backOffInitialInterval: 15000
            backOffMaxInterval: 60000
        output:
          destination: foo-result
