spring:
  application:
    name: foo-sink
  cloud:
    function:
      definition: storeFoo
    stream:
      defaultBinder: rabbit
      function:
        bindings:
          storeFoo-in-0: input
      bindings:
        input:
          destination: foo-result
          group: foo-result-group
          consumer:
            maxAttempts: 4
            backOffInitialInterval: 15000
            backOffMaxInterval: 60000
